// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MiniWalletSystem.Models;

#nullable disable

namespace MiniWalletSystem.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260613211457_AddTransactionHistory")]
    partial class AddTransactionHistory
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MiniWalletSystem.Models.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserID"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserID");

                    b.ToTable("users");
                });

            modelBuilder.Entity("MiniWalletSystem.Models.Wallet", b =>
                {
                    b.Property<int>("WalletID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WalletID"));

                    b.Property<decimal>("Balance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("WalletID");

                    b.HasIndex("UserID")
                        .IsUnique();

                    b.ToTable("wallets");
                });

            modelBuilder.Entity("MiniWalletSystem.Models.WalletTransaction", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("TransactionType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("walletID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("walletID");

                    b.ToTable("walletTransactions");
                });

            modelBuilder.Entity("MiniWalletSystem.Models.Wallet", b =>
                {
                    b.HasOne("MiniWalletSystem.Models.User", "Owner")
                        .WithOne("UserWallet")
                        .HasForeignKey("MiniWalletSystem.Models.Wallet", "UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("MiniWalletSystem.Models.WalletTransaction", b =>
                {
                    b.HasOne("MiniWalletSystem.Models.Wallet", "Wallet")
                        .WithMany("walletTransactions")
                        .HasForeignKey("walletID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("MiniWalletSystem.Models.User", b =>
                {
                    b.Navigation("UserWallet")
                        .IsRequired();
                });

            modelBuilder.Entity("MiniWalletSystem.Models.Wallet", b =>
                {
                    b.Navigation("walletTransactions");
                });
#pragma warning restore 612, 618
        }
    }
}
